// <auto-generated />
namespace _1811063275_NguyenQuangHuy_lab456.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addUpdateNew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUpdateNew));
        
        string IMigrationMetadata.Id
        {
            get { return "202107111553281_addUpdateNew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
